# Create a Pod that uses terminationGracePeriodSeconds: 30 and observe shutdown behavior.

# apiVersion: v1
# kind: Pod
# metadata:
#   name: graceful-termination-pod
# spec:
#   containers:
#   - name: busybox
#     image: busybox
#     command: ["sh", "-c", "sleep 3600"]
#   terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Pod
metadata:
  name: delayed-shutdown-pod
spec:
  terminationGracePeriodSeconds: 30
  containers:
  - name: busybox
    image: busybox
    command:
      - sh
      - -c
      - |
        trap 'echo "SIGTERM received, sleeping for 40 seconds..."; sleep 40; echo "Exiting after delay"; exit 0' TERM
        echo "Starting container, sleeping indefinitely..."
        while true; do sleep 1; done
