# Use nfs backed PV and mount in a Pod.
# Creating nfs in Mac
# sudo vi /etc/exports
# /System/Volumes/Data/nfs/kind-data -alldirs -mapall=0:0 -network 0.0.0.0 -mask 0.0.0.0
# sudo nfsd enable
# sudo nfsd update
# sudo nfsd restart
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: host.docker.internal
    path: /System/Volumes/Data/nfs/kind-data
  persistentVolumeReclaimPolicy: Delete

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: nfs-pv           # ← Important: binds to your manual PV
  storageClassName: ""         # ← Prevents dynamic provisioning

---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: [ "sh", "-c", "echo 'Hello from NFS main container!' > /mnt/nfs/hello.txt && sleep 3600" ]
      volumeMounts:
        - name: nfs-volume
          mountPath: /mnt/nfs
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc

