# Create a policy allowing egress to Pods labeled db=true.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-policy-db
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          db: true