# Allow ingress traffic from 10.244.0.0/16 CIDR block.

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-from-cidr
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.244.0.0/16