# Allow ingress only on port 443.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-on-port
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 443