# Add a readinessProbe to pause traffic during start.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - containerPort: 80
          readinessProbe:
            exec:
              command:
                - cat
                - /var/run/nginx.pid
            initialDelaySeconds: 5
            periodSeconds: 10
