# Inject ConfigMap into Deployment containers via envFrom.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
data:
  name: shubham
  branch: cse

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx
          envFrom:
          - configMapRef:
              name: cm
