# Inject Secret as volume in Deployment.

---
apiVersion: v1
kind: Secret
metadata:
  name: sec
type: Opaque
data:
  name: c2h1YmhhbQ==
  branch: Y3Nl

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: sec
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - mountPath: "/etc/secret-volume"
              name: secret-volume
              readOnly: true
