# Add annotations and labels to Deployment metadata.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: web
    tier: frontend
    env: prod
  annotations:
    created-by: "shubham"
    git-commit-hash: "a1b2c3d4"
    kubernetes.io/change-casue: "Initial Rollout"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        config-checksum: "1234567890"
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

    
