# Set resource requests and limits.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    app: web
    tier: frontend
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels: 
        app: web
    spec:
      # Pod level pe requests and limits
      resources:
        limits:
          cpu: "1"
          memory: "200Mi"
        requests:
          cpu: "1"
          memory: "100Mi"
      containers:
      - name: nginx
        image: nginx
        # container level pe request and limits
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m" # 1cpu = 1000m
          limits:
            memory: "128Mi"
            cpu: "500m"

