# Add initContainers in Deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-init
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["echo 'I am init Containers'; sleep 10"]
      containers:
      - name: nginx
        image: nginx
