# Use antiAffinity to distribute Pods across nodes.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution: # soft
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: web-container
          image: nginx


# affinity:
#   podAntiAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution: #hard
#       - labelSelector:
#           matchExpressions:
#             - key: app
#               operator: In
#               values:
#                 - web
#         topologyKey: "kubernetes.io/hostname"
