# Observe preemption of low-priority Pods.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-priority-pod
spec:
  selector:
    matchLabels:
      app: web
  replicas: 10
  template:
    metadata:
      labels:
        app: web
    spec:
      priorityClassName: custom-priorityclass
      containers:
      - name: nginx
        image: nginx

# scaling the replicas of current deployment lead to termination of the pods which has lower priority