# Reserve CPU using resource requests.

apiVersion: v1
kind: Pod
metadata:
  name: pod-resource
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: 250m
          memory: 250Mi