# Schedule Pod with resource limits only.

apiVersion: v1
kind: Pod
metadata:
  name: pod-resource2
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: 250m
          memory: 250Mi